# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEvent.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(608, 412)
        self.okcanButtons = QtWidgets.QDialogButtonBox(Dialog)
        self.okcanButtons.setGeometry(QtCore.QRect(490, 10, 81, 241))
        self.okcanButtons.setOrientation(QtCore.Qt.Vertical)
        self.okcanButtons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.okcanButtons.setObjectName("okcanButtons")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 30, 55, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 91, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 60, 55, 16))
        self.label_3.setObjectName("label_3")
        self.calendarEd = QtWidgets.QCalendarWidget(Dialog)
        self.calendarEd.setGeometry(QtCore.QRect(260, 80, 312, 183))
        self.calendarEd.setObjectName("calendarEd")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(260, 50, 91, 16))
        self.label_4.setObjectName("label_4")
        self.timeEditComb = QtWidgets.QTimeEdit(Dialog)
        self.timeEditComb.setGeometry(QtCore.QRect(270, 300, 118, 22))
        self.timeEditComb.setObjectName("timeEditComb")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(270, 270, 101, 16))
        self.label_5.setObjectName("label_5")
        self.ifRemindBox = QtWidgets.QCheckBox(Dialog)
        self.ifRemindBox.setGeometry(QtCore.QRect(110, 90, 77, 20))
        self.ifRemindBox.setText("")
        self.ifRemindBox.setObjectName("ifRemindBox")
        self.remindComb = QtWidgets.QComboBox(Dialog)
        self.remindComb.setGeometry(QtCore.QRect(20, 140, 201, 22))
        self.remindComb.setObjectName("remindComb")
        self.remindComb.addItem("")
        self.remindComb.addItem("")
        self.remindComb.addItem("")
        self.remindComb.addItem("")
        self.remindComb.addItem("")
        self.remindComb.addItem("")
        self.remindComb.addItem("")
        self.remindComb.addItem("")
        self.remindComb.addItem("")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(20, 120, 111, 16))
        self.label_6.setObjectName("label_6")
        self.catCombo = QtWidgets.QComboBox(Dialog)
        self.catCombo.setGeometry(QtCore.QRect(90, 60, 131, 22))
        self.catCombo.setObjectName("catCombo")
        self.lineDesc = QtWidgets.QLineEdit(Dialog)
        self.lineDesc.setGeometry(QtCore.QRect(90, 30, 131, 22))
        self.lineDesc.setText("")
        self.lineDesc.setObjectName("lineDesc")

        self.retranslateUi(Dialog)
        self.okcanButtons.accepted.connect(Dialog.accept) # type: ignore
        self.okcanButtons.rejected.connect(Dialog.reject) # type: ignore
        self.ifRemindBox.toggled['bool'].connect(Dialog.execRem) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Opis"))
        self.label_2.setText(_translate("Dialog", "Przypomnienie"))
        self.label_3.setText(_translate("Dialog", "Kategoria"))
        self.label_4.setText(_translate("Dialog", "Wybierz dzień"))
        self.label_5.setText(_translate("Dialog", "Wybierz godzinę"))
        self.remindComb.setItemText(0, _translate("Dialog", "Godzinę przed"))
        self.remindComb.setItemText(1, _translate("Dialog", "12 godzin przed"))
        self.remindComb.setItemText(2, _translate("Dialog", "Dzień przed"))
        self.remindComb.setItemText(3, _translate("Dialog", "Dwa dni przed"))
        self.remindComb.setItemText(4, _translate("Dialog", "Pięć dni przed"))
        self.remindComb.setItemText(5, _translate("Dialog", "Tydzień przed"))
        self.remindComb.setItemText(6, _translate("Dialog", "Dwa tygodnie przed"))
        self.remindComb.setItemText(7, _translate("Dialog", "Miesiąc przed"))
        self.remindComb.setItemText(8, _translate("Dialog", "Rok przed"))
        self.label_6.setText(_translate("Dialog", "Kiedy przypomnieć"))
