# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(879, 608)
        self.listView = QtWidgets.QListView(Dialog)
        self.listView.setGeometry(QtCore.QRect(280, -10, 601, 631))
        self.listView.setObjectName("listView")
        self.pushRemoveCat = QtWidgets.QPushButton(Dialog)
        self.pushRemoveCat.setGeometry(QtCore.QRect(150, 580, 101, 28))
        self.pushRemoveCat.setObjectName("pushRemoveCat")
        self.pushAddCat = QtWidgets.QPushButton(Dialog)
        self.pushAddCat.setGeometry(QtCore.QRect(20, 580, 101, 28))
        self.pushAddCat.setObjectName("pushAddCat")
        self.SelectCatBox = QtWidgets.QComboBox(Dialog)
        self.SelectCatBox.setGeometry(QtCore.QRect(30, 10, 221, 22))
        self.SelectCatBox.setObjectName("SelectCatBox")
        self.textEditCat = QtWidgets.QTextEdit(Dialog)
        self.textEditCat.setGeometry(QtCore.QRect(20, 550, 101, 21))
        self.textEditCat.setObjectName("textEditCat")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 530, 101, 16))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(130, 540, 131, 31))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        self.pushButton.pressed.connect(Dialog.open) # type: ignore
        self.SelectCatBox.activated[str].connect(self.onChanged)
        self.pushRemoveCat.clicked.connect(Dialog.execRem) # type: ignore
        self.pushAddCat.clicked.connect(Dialog.execAdd) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushRemoveCat.setText(_translate("Dialog", "Usuń kategorię"))
        self.pushAddCat.setText(_translate("Dialog", "Dodaj kategorię"))
        self.label.setText(_translate("Dialog", "Nowa Kategoria:"))
        self.pushButton.setText(_translate("Dialog", "Dodaj wydarzenie"))
